[2025-02-17T16:56:20.386+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T16:56:20.400+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-16T00:00:00+00:00 [queued]>
[2025-02-17T16:56:20.406+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-16T00:00:00+00:00 [queued]>
[2025-02-17T16:56:20.407+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-17T16:56:20.423+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_dim_location> on 2025-02-16 00:00:00+00:00
[2025-02-17T16:56:20.427+0000] {standard_task_runner.py:72} INFO - Started process 75 to run task
[2025-02-17T16:56:20.430+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_dim_location', 'scheduled__2025-02-16T00:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpjtiolta5']
[2025-02-17T16:56:20.432+0000] {standard_task_runner.py:105} INFO - Job 254: Subtask run_dbt_dim_location
[2025-02-17T16:56:20.451+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-17T16:56:20.490+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-16T00:00:00+00:00 [running]> on host fd8844a481fe
[2025-02-17T16:56:20.492+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-17T16:56:20.590+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_dim_location' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-16T00:00:00+00:00'
[2025-02-17T16:56:20.591+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-17T16:56:20.645+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-17T16:56:20.647+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select dim_location']
[2025-02-17T16:56:20.653+0000] {subprocess.py:99} INFO - Output:
[2025-02-17T16:56:23.809+0000] {subprocess.py:106} INFO - [0m16:56:23  Running with dbt=1.9.2
[2025-02-17T16:56:24.316+0000] {subprocess.py:106} INFO - [0m16:56:24  Registered adapter: postgres=1.9.0
[2025-02-17T16:56:24.598+0000] {subprocess.py:106} INFO - [0m16:56:24  Unable to do partial parsing because profile has changed
[2025-02-17T16:56:24.599+0000] {subprocess.py:106} INFO - [0m16:56:24  Unable to do partial parsing because a project config has changed
[2025-02-17T16:56:30.432+0000] {subprocess.py:106} INFO - [0m16:56:30  Found 7 models, 34 data tests, 1 source, 632 macros
[2025-02-17T16:56:30.436+0000] {subprocess.py:106} INFO - [0m16:56:30
[2025-02-17T16:56:30.436+0000] {subprocess.py:106} INFO - [0m16:56:30  Concurrency: 1 threads (target='prod')
[2025-02-17T16:56:30.437+0000] {subprocess.py:106} INFO - [0m16:56:30
[2025-02-17T16:56:30.590+0000] {subprocess.py:106} INFO - [0m16:56:30  1 of 1 START sql incremental model core.dim_location ........................... [RUN]
[2025-02-17T16:56:30.835+0000] {subprocess.py:106} INFO - [0m16:56:30  1 of 1 OK created sql incremental model core.dim_location ...................... [[32mINSERT 0 0[0m in 0.24s]
[2025-02-17T16:56:30.850+0000] {subprocess.py:106} INFO - [0m16:56:30
[2025-02-17T16:56:30.850+0000] {subprocess.py:106} INFO - [0m16:56:30  Finished running 1 incremental model in 0 hours 0 minutes and 0.41 seconds (0.41s).
[2025-02-17T16:56:30.944+0000] {subprocess.py:106} INFO - [0m16:56:30
[2025-02-17T16:56:30.945+0000] {subprocess.py:106} INFO - [0m16:56:30  [32mCompleted successfully[0m
[2025-02-17T16:56:30.947+0000] {subprocess.py:106} INFO - [0m16:56:30
[2025-02-17T16:56:30.947+0000] {subprocess.py:106} INFO - [0m16:56:30  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-17T16:56:32.190+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-17T16:56:32.220+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-17T16:56:32.221+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_dim_location, run_id=scheduled__2025-02-16T00:00:00+00:00, execution_date=20250216T000000, start_date=20250217T165620, end_date=20250217T165632
[2025-02-17T16:56:32.284+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-17T16:56:32.314+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-17T16:56:32.317+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-17T16:56:38.688+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-17T16:56:38.704+0000] {taskinstance.py:2604} INFO - Dependencies not met for <TaskInstance: superstore_dag.run_dbt_dim_location scheduled__2025-02-16T00:00:00+00:00 [success]>, dependency 'Task Instance State' FAILED: Task is in the 'success' state.
[2025-02-17T16:56:38.707+0000] {local_task_job_runner.py:166} INFO - Task is not able to be run
