[2025-02-16T17:45:08.154+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-16T17:45:08.183+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-16T17:44:13.179593+00:00 [queued]>
[2025-02-16T17:45:08.200+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-16T17:44:13.179593+00:00 [queued]>
[2025-02-16T17:45:08.201+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-16T17:45:08.214+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): run_dbt_fact_orders> on 2025-02-16 17:44:13.179593+00:00
[2025-02-16T17:45:08.219+0000] {standard_task_runner.py:72} INFO - Started process 1624 to run task
[2025-02-16T17:45:08.223+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_fact_orders', 'manual__2025-02-16T17:44:13.179593+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpkjs9pl41']
[2025-02-16T17:45:08.225+0000] {standard_task_runner.py:105} INFO - Job 250: Subtask run_dbt_fact_orders
[2025-02-16T17:45:08.239+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-16T17:45:08.273+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-16T17:44:13.179593+00:00 [running]> on host e06c424a4719
[2025-02-16T17:45:08.351+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T17:44:13.179593+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T17:44:13.179593+00:00'
[2025-02-16T17:45:08.352+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-16T17:45:08.367+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-16T17:45:08.368+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select fact_orders']
[2025-02-16T17:45:08.379+0000] {subprocess.py:99} INFO - Output:
[2025-02-16T17:45:10.453+0000] {subprocess.py:106} INFO - [0m17:45:10  Running with dbt=1.9.2
[2025-02-16T17:45:10.747+0000] {subprocess.py:106} INFO - [0m17:45:10  Registered adapter: postgres=1.9.0
[2025-02-16T17:45:12.600+0000] {subprocess.py:106} INFO - [0m17:45:12  Found 7 models, 34 data tests, 1 source, 632 macros
[2025-02-16T17:45:12.604+0000] {subprocess.py:106} INFO - [0m17:45:12
[2025-02-16T17:45:12.605+0000] {subprocess.py:106} INFO - [0m17:45:12  Concurrency: 1 threads (target='prod')
[2025-02-16T17:45:12.606+0000] {subprocess.py:106} INFO - [0m17:45:12
[2025-02-16T17:45:12.730+0000] {subprocess.py:106} INFO - [0m17:45:12  1 of 1 START sql incremental model core.fact_orders ............................ [RUN]
[2025-02-16T17:45:12.989+0000] {subprocess.py:106} INFO - [0m17:45:12  1 of 1 OK created sql incremental model core.fact_orders ....................... [[32mINSERT 0 0[0m in 0.26s]
[2025-02-16T17:45:13.004+0000] {subprocess.py:106} INFO - [0m17:45:13
[2025-02-16T17:45:13.005+0000] {subprocess.py:106} INFO - [0m17:45:13  Finished running 1 incremental model in 0 hours 0 minutes and 0.40 seconds (0.40s).
[2025-02-16T17:45:13.087+0000] {subprocess.py:106} INFO - [0m17:45:13
[2025-02-16T17:45:13.088+0000] {subprocess.py:106} INFO - [0m17:45:13  [32mCompleted successfully[0m
[2025-02-16T17:45:13.089+0000] {subprocess.py:106} INFO - [0m17:45:13
[2025-02-16T17:45:13.090+0000] {subprocess.py:106} INFO - [0m17:45:13  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-16T17:45:14.026+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-16T17:45:14.051+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-16T17:45:14.051+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_fact_orders, run_id=manual__2025-02-16T17:44:13.179593+00:00, execution_date=20250216T174413, start_date=20250216T174508, end_date=20250216T174514
[2025-02-16T17:45:14.085+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-16T17:45:14.110+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-16T17:45:14.112+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
