[2025-02-08T17:50:01.873+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-08T17:50:01.884+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_location.run_dbt_fact_orders manual__2025-02-08T17:49:35.402228+00:00 [queued]>
[2025-02-08T17:50:01.890+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_location.run_dbt_fact_orders manual__2025-02-08T17:49:35.402228+00:00 [queued]>
[2025-02-08T17:50:01.891+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-08T17:50:01.903+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_fact_orders> on 2025-02-08 17:49:35.402228+00:00
[2025-02-08T17:50:01.908+0000] {standard_task_runner.py:72} INFO - Started process 741 to run task
[2025-02-08T17:50:01.910+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dim_location', 'run_dbt_fact_orders', 'manual__2025-02-08T17:49:35.402228+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/dim_location.py', '--cfg-path', '/tmp/tmpkm83qqxg']
[2025-02-08T17:50:01.911+0000] {standard_task_runner.py:105} INFO - Job 189: Subtask run_dbt_fact_orders
[2025-02-08T17:50:01.922+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-08T17:50:01.947+0000] {task_command.py:467} INFO - Running <TaskInstance: dim_location.run_dbt_fact_orders manual__2025-02-08T17:49:35.402228+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-08T17:50:02.006+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_location' AIRFLOW_CTX_TASK_ID='run_dbt_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T17:49:35.402228+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-08T17:49:35.402228+00:00'
[2025-02-08T17:50:02.007+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-08T17:50:02.019+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-08T17:50:02.020+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select fact_orders']
[2025-02-08T17:50:02.027+0000] {subprocess.py:99} INFO - Output:
[2025-02-08T17:50:06.265+0000] {subprocess.py:106} INFO - [0m17:50:06  Running with dbt=1.9.2
[2025-02-08T17:50:06.478+0000] {subprocess.py:106} INFO - [0m17:50:06  Registered adapter: postgres=1.9.0
[2025-02-08T17:50:06.699+0000] {subprocess.py:106} INFO - [0m17:50:06  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-08T17:50:06.700+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-08T17:50:06.700+0000] {subprocess.py:106} INFO - - models.superstore_project.dim_customer
[2025-02-08T17:50:06.833+0000] {subprocess.py:106} INFO - [0m17:50:06  Found 5 models, 8 data tests, 1 source, 431 macros
[2025-02-08T17:50:06.836+0000] {subprocess.py:106} INFO - [0m17:50:06
[2025-02-08T17:50:06.841+0000] {subprocess.py:106} INFO - [0m17:50:06  Concurrency: 1 threads (target='prod')
[2025-02-08T17:50:06.841+0000] {subprocess.py:106} INFO - [0m17:50:06
[2025-02-08T17:50:06.914+0000] {subprocess.py:106} INFO - [0m17:50:06  1 of 1 START sql incremental model core.fact_orders ............................ [RUN]
[2025-02-08T17:50:07.086+0000] {subprocess.py:106} INFO - [0m17:50:07  1 of 1 OK created sql incremental model core.fact_orders ....................... [[32mINSERT 0 0[0m in 0.17s]
[2025-02-08T17:50:07.097+0000] {subprocess.py:106} INFO - [0m17:50:07
[2025-02-08T17:50:07.097+0000] {subprocess.py:106} INFO - [0m17:50:07  Finished running 1 incremental model in 0 hours 0 minutes and 0.25 seconds (0.25s).
[2025-02-08T17:50:07.140+0000] {subprocess.py:106} INFO - [0m17:50:07
[2025-02-08T17:50:07.141+0000] {subprocess.py:106} INFO - [0m17:50:07  [32mCompleted successfully[0m
[2025-02-08T17:50:07.146+0000] {subprocess.py:106} INFO - [0m17:50:07
[2025-02-08T17:50:07.148+0000] {subprocess.py:106} INFO - [0m17:50:07  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-08T17:50:07.949+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-08T17:50:07.971+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-08T17:50:07.972+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=dim_location, task_id=run_dbt_fact_orders, run_id=manual__2025-02-08T17:49:35.402228+00:00, execution_date=20250208T174935, start_date=20250208T175001, end_date=20250208T175007
[2025-02-08T17:50:08.018+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-08T17:50:08.031+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-08T17:50:08.034+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
