[2025-02-11T18:25:51.663+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T18:25:51.678+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-11T18:24:30.820415+00:00 [queued]>
[2025-02-11T18:25:51.686+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-11T18:24:30.820415+00:00 [queued]>
[2025-02-11T18:25:51.689+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-11T18:25:51.700+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_fact_orders> on 2025-02-11 18:24:30.820415+00:00
[2025-02-11T18:25:51.707+0000] {standard_task_runner.py:72} INFO - Started process 793 to run task
[2025-02-11T18:25:51.710+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_fact_orders', 'manual__2025-02-11T18:24:30.820415+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmpd9acn9ob']
[2025-02-11T18:25:51.712+0000] {standard_task_runner.py:105} INFO - Job 209: Subtask run_dbt_fact_orders
[2025-02-11T18:25:51.727+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T18:25:51.757+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-11T18:24:30.820415+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-11T18:25:51.822+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T18:24:30.820415+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T18:24:30.820415+00:00'
[2025-02-11T18:25:51.823+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T18:25:51.835+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-11T18:25:51.836+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select fact_orders']
[2025-02-11T18:25:51.844+0000] {subprocess.py:99} INFO - Output:
[2025-02-11T18:25:53.841+0000] {subprocess.py:106} INFO - [0m18:25:53  Running with dbt=1.9.2
[2025-02-11T18:25:54.114+0000] {subprocess.py:106} INFO - [0m18:25:54  Registered adapter: postgres=1.9.0
[2025-02-11T18:25:54.394+0000] {subprocess.py:106} INFO - [0m18:25:54  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-11T18:25:54.395+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-11T18:25:54.395+0000] {subprocess.py:106} INFO - - models.superstore_project.dim_product
[2025-02-11T18:25:54.590+0000] {subprocess.py:106} INFO - [0m18:25:54  Found 5 models, 8 data tests, 1 source, 431 macros
[2025-02-11T18:25:54.616+0000] {subprocess.py:106} INFO - [0m18:25:54
[2025-02-11T18:25:54.617+0000] {subprocess.py:106} INFO - [0m18:25:54  Concurrency: 1 threads (target='prod')
[2025-02-11T18:25:54.618+0000] {subprocess.py:106} INFO - [0m18:25:54
[2025-02-11T18:25:54.710+0000] {subprocess.py:106} INFO - [0m18:25:54  1 of 1 START sql incremental model core.fact_orders ............................ [RUN]
[2025-02-11T18:25:54.894+0000] {subprocess.py:106} INFO - [0m18:25:54  1 of 1 OK created sql incremental model core.fact_orders ....................... [[32mINSERT 0 0[0m in 0.18s]
[2025-02-11T18:25:54.907+0000] {subprocess.py:106} INFO - [0m18:25:54
[2025-02-11T18:25:54.908+0000] {subprocess.py:106} INFO - [0m18:25:54  Finished running 1 incremental model in 0 hours 0 minutes and 0.29 seconds (0.29s).
[2025-02-11T18:25:54.967+0000] {subprocess.py:106} INFO - [0m18:25:54
[2025-02-11T18:25:54.967+0000] {subprocess.py:106} INFO - [0m18:25:54  [32mCompleted successfully[0m
[2025-02-11T18:25:54.968+0000] {subprocess.py:106} INFO - [0m18:25:54
[2025-02-11T18:25:54.968+0000] {subprocess.py:106} INFO - [0m18:25:54  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-11T18:25:55.888+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-11T18:25:55.912+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T18:25:55.913+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_fact_orders, run_id=manual__2025-02-11T18:24:30.820415+00:00, execution_date=20250211T182430, start_date=20250211T182551, end_date=20250211T182555
[2025-02-11T18:25:55.935+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T18:25:55.953+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T18:25:55.956+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
