[2025-02-11T18:36:18.257+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T18:36:18.270+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-11T18:24:30.820415+00:00 [queued]>
[2025-02-11T18:36:18.277+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-11T18:24:30.820415+00:00 [queued]>
[2025-02-11T18:36:18.278+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-11T18:36:18.289+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): run_dbt_fact_orders> on 2025-02-11 18:24:30.820415+00:00
[2025-02-11T18:36:18.295+0000] {standard_task_runner.py:72} INFO - Started process 863 to run task
[2025-02-11T18:36:18.301+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'superstore_dag', 'run_dbt_fact_orders', 'manual__2025-02-11T18:24:30.820415+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/superstore_dag.py', '--cfg-path', '/tmp/tmp3xsm31bo']
[2025-02-11T18:36:18.307+0000] {standard_task_runner.py:105} INFO - Job 210: Subtask run_dbt_fact_orders
[2025-02-11T18:36:18.332+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-11T18:36:18.370+0000] {task_command.py:467} INFO - Running <TaskInstance: superstore_dag.run_dbt_fact_orders manual__2025-02-11T18:24:30.820415+00:00 [running]> on host 9cd0ccfaeb2e
[2025-02-11T18:36:18.454+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='superstore_dag' AIRFLOW_CTX_TASK_ID='run_dbt_fact_orders' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T18:24:30.820415+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T18:24:30.820415+00:00'
[2025-02-11T18:36:18.455+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-11T18:36:18.472+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-11T18:36:18.473+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /dbt/superstore/ && dbt run --select fact_orders']
[2025-02-11T18:36:18.481+0000] {subprocess.py:99} INFO - Output:
[2025-02-11T18:36:20.743+0000] {subprocess.py:106} INFO - [0m18:36:20  Running with dbt=1.9.2
[2025-02-11T18:36:21.073+0000] {subprocess.py:106} INFO - [0m18:36:21  Registered adapter: postgres=1.9.0
[2025-02-11T18:36:21.779+0000] {subprocess.py:106} INFO - [0m18:36:21  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-02-11T18:36:21.779+0000] {subprocess.py:106} INFO - There are 1 unused configuration paths:
[2025-02-11T18:36:21.780+0000] {subprocess.py:106} INFO - - models.superstore_project.dim_product
[2025-02-11T18:36:21.969+0000] {subprocess.py:106} INFO - [0m18:36:21  Found 5 models, 8 data tests, 1 source, 431 macros
[2025-02-11T18:36:21.976+0000] {subprocess.py:106} INFO - [0m18:36:21
[2025-02-11T18:36:21.977+0000] {subprocess.py:106} INFO - [0m18:36:21  Concurrency: 1 threads (target='prod')
[2025-02-11T18:36:21.978+0000] {subprocess.py:106} INFO - [0m18:36:21
[2025-02-11T18:36:22.109+0000] {subprocess.py:106} INFO - [0m18:36:22  1 of 1 START sql incremental model core.fact_orders ............................ [RUN]
[2025-02-11T18:36:22.498+0000] {subprocess.py:106} INFO - [0m18:36:22  1 of 1 OK created sql incremental model core.fact_orders ....................... [[32mINSERT 0 10672[0m in 0.38s]
[2025-02-11T18:36:22.517+0000] {subprocess.py:106} INFO - [0m18:36:22
[2025-02-11T18:36:22.520+0000] {subprocess.py:106} INFO - [0m18:36:22  Finished running 1 incremental model in 0 hours 0 minutes and 0.54 seconds (0.54s).
[2025-02-11T18:36:22.599+0000] {subprocess.py:106} INFO - [0m18:36:22
[2025-02-11T18:36:22.600+0000] {subprocess.py:106} INFO - [0m18:36:22  [32mCompleted successfully[0m
[2025-02-11T18:36:22.601+0000] {subprocess.py:106} INFO - [0m18:36:22
[2025-02-11T18:36:22.602+0000] {subprocess.py:106} INFO - [0m18:36:22  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-02-11T18:36:23.641+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-11T18:36:23.664+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-11T18:36:23.665+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=superstore_dag, task_id=run_dbt_fact_orders, run_id=manual__2025-02-11T18:24:30.820415+00:00, execution_date=20250211T182430, start_date=20250211T183618, end_date=20250211T183623
[2025-02-11T18:36:23.692+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T18:36:23.706+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T18:36:23.708+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
