[0m00:19:22.596226 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BEEA45A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BECC0CF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BEFB83ED0>]}


============================== 00:19:22.602621 | 8674c40a-0095-454c-91ab-05afeb37bcda ==============================
[0m00:19:22.602621 [info ] [MainThread]: Running with dbt=1.9.2
[0m00:19:22.603355 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\Ivan\\.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m00:19:22.638814 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object, got 'WindowsPath'.. Dictionary: {'dir': WindowsPath('C:/Users/Ivan/.dbt')}
[0m00:19:22.639539 [info ] [MainThread]: Creating dbt configuration folder at 
[0m00:19:32.995033 [debug] [MainThread]: Starter project path: C:\Users\Ivan\AppData\Local\Programs\Python\Python313\Lib\site-packages\dbt\include\starter_project
[0m00:19:33.022149 [info ] [MainThread]: 
Your new dbt project "superstore" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:19:33.023637 [info ] [MainThread]: Setting up your profile.
[0m00:20:35.661515 [info ] [MainThread]: Profile superstore written to C:\Users\Ivan\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:20:35.662811 [debug] [MainThread]: Command `dbt init` succeeded at 00:20:35.662664 after 73.24 seconds
[0m00:20:35.663160 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BEFDE96E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BEFC17770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020BEFA428B0>]}
[0m00:20:35.663511 [debug] [MainThread]: Flushing usage events
[0m00:20:36.468796 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:41:44.231195 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F98E085A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F98C24CF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F98F1C3ED0>]}


============================== 00:41:44.236090 | 4cd52f75-b1de-40c7-957a-0dda24d97057 ==============================
[0m00:41:44.236090 [info ] [MainThread]: Running with dbt=1.9.2
[0m00:41:44.236722 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Ivan\\Documents\\docker_projects\\first_data_project\\dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m00:41:44.237185 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Ivan\Documents\docker_projects\first_data_project\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:41:44.238133 [debug] [MainThread]: Command `dbt run` failed at 00:41:44.237991 after 0.17 seconds
[0m00:41:44.238496 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F98F1DD5B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F98F03F1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002F98F081E10>]}
[0m00:41:44.238807 [debug] [MainThread]: Flushing usage events
[0m00:41:44.854419 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:15:34.183367 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002230DF25A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002230C104F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002230F077ED0>]}


============================== 02:15:34.190906 | 5b695fac-560a-4078-a721-011e22d42e73 ==============================
[0m02:15:34.190906 [info ] [MainThread]: Running with dbt=1.9.2
[0m02:15:34.191879 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Ivan\\Documents\\docker_projects\\first_data_project\\dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt test --select dim_location', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m02:15:34.192299 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Ivan\Documents\docker_projects\first_data_project\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:15:34.193452 [debug] [MainThread]: Command `dbt test` failed at 02:15:34.193329 after 0.30 seconds
[0m02:15:34.193753 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002230F0895B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002230EEEF1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002230EF31E10>]}
[0m02:15:34.194059 [debug] [MainThread]: Flushing usage events
[0m02:15:35.248061 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m02:16:00.271618 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DB2305A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DB0518F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DB3443ED0>]}


============================== 02:16:00.276049 | 4ccac800-82b7-4cae-8cc7-489fbad78c48 ==============================
[0m02:16:00.276049 [info ] [MainThread]: Running with dbt=1.9.2
[0m02:16:00.276740 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Ivan\\Documents\\docker_projects\\first_data_project\\dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select dim_location', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m02:16:00.277126 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Ivan\Documents\docker_projects\first_data_project\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m02:16:00.278094 [debug] [MainThread]: Command `dbt run` failed at 02:16:00.277983 after 0.17 seconds
[0m02:16:00.278399 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DB34595B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DB32BF1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000016DB3301E10>]}
[0m02:16:00.278683 [debug] [MainThread]: Flushing usage events
[0m02:16:01.156365 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m16:52:34.294596 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16d31411c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16d2cdffb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16d2bf7260>]}


============================== 16:52:34.306286 | efef181e-0317-471e-acc2-cdabcd41cbe3 ==============================
[0m16:52:34.306286 [info ] [MainThread]: Running with dbt=1.9.2
[0m16:52:34.307099 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select dim_location', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:52:34.307856 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:52:34.308820 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.113556616, "process_in_blocks": "56", "process_kernel_time": 0.21819, "process_mem_max_rss": "97940", "process_out_blocks": "0", "process_user_time": 1.592792}
[0m16:52:34.309385 [debug] [MainThread]: Command `dbt run` failed at 16:52:34.309300 after 0.11 seconds
[0m16:52:34.309811 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16d4a3c6e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16d2cdffb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f16d2b75fa0>]}
[0m16:52:34.310304 [debug] [MainThread]: Flushing usage events
[0m16:52:34.979820 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:38:13.659388 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024FC185DA90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024FBFA14F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024FC2993ED0>]}


============================== 20:38:13.668126 | 697c1fe6-9a23-4cc0-919f-29f2059aa4b4 ==============================
[0m20:38:13.668126 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:38:13.670859 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Ivan\\Documents\\docker_projects\\first_data_project\\dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:38:13.671652 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Ivan\Documents\docker_projects\first_data_project\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:38:13.673322 [debug] [MainThread]: Command `dbt run` failed at 20:38:13.673193 after 0.20 seconds
[0m20:38:13.673647 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024FC29AD5B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024FC280F1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024FC2851E10>]}
[0m20:38:13.673957 [debug] [MainThread]: Flushing usage events
[0m20:38:14.476077 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m20:38:12.733333 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209E9D51A90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209E7F18F50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209EAEA3ED0>]}


============================== 20:38:12.741043 | b614d9d1-e61d-44da-9e0b-63178c415c85 ==============================
[0m20:38:12.741043 [info ] [MainThread]: Running with dbt=1.9.2
[0m20:38:12.742015 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Ivan\\Documents\\docker_projects\\first_data_project\\dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select categories_pivot_t', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:38:12.742701 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Ivan\Documents\docker_projects\first_data_project\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:38:12.743532 [debug] [MainThread]: Command `dbt run` failed at 20:38:12.743409 after 0.20 seconds
[0m20:38:12.743811 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209EAEB95B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209EAD1F1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209EAD61E10>]}
[0m20:38:12.744096 [debug] [MainThread]: Flushing usage events
[0m20:38:13.460227 [debug] [MainThread]: An error was encountered while trying to flush usage events
